version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  commit-message:
    prefix: "chore"
    include: "scope"

- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
    day: "monday"
  open-pull-requests-limit: 10
  commit-message:
    prefix: "chore"
    include: "scope"
  # Monitor version catalog files
  # Block major updates for Netty modules (breaking changes risk)
  # Block all updates for ICU4J (stability requirement)
  ignore:
    - dependency-name: "netty-buffer"
      update-types: ["version-update:semver-major"]
    - dependency-name: "netty-common"
      update-types: ["version-update:semver-major"]
    - dependency-name: "netty-transport"
      update-types: ["version-update:semver-major"]
    - dependency-name: "netty-codec-http"
      update-types: ["version-update:semver-major"]
    - dependency-name: "netty-handler"
      update-types: ["version-update:semver-major"]
    - dependency-name: "netty-handler-timeout"
      update-types: ["version-update:semver-major"]
    - dependency-name: "icu4j"
      update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]
  # Group updates for better PR management
  groups:
    gradle-dependencies:
      patterns:
        - "*"
      update-types:
        - "version-update:semver-minor"
        - "version-update:semver-patch"

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
    day: "tuesday"
  open-pull-requests-limit: 5
  commit-message:
    prefix: "chore"
    include: "scope"
  # Group GitHub Actions updates
  groups:
    github-actions:
      patterns:
        - "*"
      update-types:
        - "version-update:semver-major"
        - "version-update:semver-minor"
        - "version-update:semver-patch"
